=== dweichert/holidayChecker/share/holidays.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://heigl.org/holidays"
           xmlns="https://heigl.org/holidays"
           elementFormDefault="qualified">
    <xs:simpleType name="monthInt">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="12"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="dayInt">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="31"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="daynames">
        <xs:restriction base="xs:string">
            <xs:enumeration value="sunday"/>
            <xs:enumeration value="monday"/>
            <xs:enumeration value="tuesday"/>
            <xs:enumeration value="wednesday"/>
            <xs:enumeration value="thursday"/>
            <xs:enumeration value="friday"/>
            <xs:enumeration value="saturday"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="daynamelist">
        <xs:list itemType="daynames" />
    </xs:simpleType>
    <xs:simpleType name="calendars">
        <xs:restriction base="xs:string">
			<!--
			as described in the language files of ICU
			see https://github.com/unicode-org/icu/blob/d453c12bfacde783b7e985cdb4eb15c6db277f78/icu4c/source/data/lang/en.txt#L951-L970
			-->
            <xs:enumeration value="buddhist"/>
            <xs:enumeration value="chinese"/>
            <xs:enumeration value="coptic"/>
            <xs:enumeration value="dangi"/>
            <xs:enumeration value="ethiopic"/>
            <xs:enumeration value="ethiopic-amete-alem"/>
            <xs:enumeration value="gregorian"/>
            <xs:enumeration value="hebrew"/>
            <xs:enumeration value="indian"/>
            <xs:enumeration value="islamic"/>
            <xs:enumeration value="islamic-civil"/>
            <xs:enumeration value="islamic-umalqura"/>
            <xs:enumeration value="islamic-tbla"/>
            <xs:enumeration value="iso8601"/>
            <xs:enumeration value="japanese"/>
            <xs:enumeration value="persian"/>
            <xs:enumeration value="roc"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:attributeGroup name="restriction">
        <xs:attribute name="restriction" type="xs:string" />
    </xs:attributeGroup>
	<xs:attribute name="firstobservance" type="xs:gYear"/>
	<xs:attribute name="lastobservance" type="xs:gYear"/>
    <xs:attributeGroup name="observanceRestrictions">
		<xs:annotation xml:lang="en">
			<xs:documentation>
				The attributes firstobservance and lastobservance are including.
				The attribute interval describes that the holiday is only observed every $interval years with the first observance in year $firstobservance.
			</xs:documentation>
		</xs:annotation>
        <xs:attribute name="firstobservance" type="xs:gYear"/>
        <xs:attribute name="lastobservance" type="xs:gYear"/>
		<xs:attribute name="interval" type="xs:integer"/>
    </xs:attributeGroup>
	<xs:attributeGroup name="observanceInterval">
		<xs:attribute ref="firstobservance" use="required"/>
	</xs:attributeGroup>
    <xs:attributeGroup name="easterAttributes">
        <xs:attribute name="offset" type="xs:integer" use="required"/>
        <xs:attribute name="free" type="xs:boolean" use="required"/>
        <xs:attribute name="comment" type="xs:string"/>
    </xs:attributeGroup>
    <xs:attributeGroup name="dateAttributes">
        <xs:attribute name="day" type="dayInt" use="required"/>
        <xs:attribute name="month" type="monthInt" use="required"/>
        <xs:attribute name="year" type="xs:integer" />
        <xs:attribute name="free" type="xs:boolean" use="required"/>
        <xs:attribute name="comment" type="xs:string"/>
        <xs:attribute name="calendar" type="calendars"/>
    </xs:attributeGroup>
    <xs:attributeGroup name="dateFollowUpAttributes">
        <xs:attribute name="day" type="dayInt" use="required"/>
        <xs:attribute name="month" type="monthInt" use="required"/>
        <xs:attribute name="followup" type="daynames" use="required" />
        <xs:attribute name="replaced" type="daynamelist" use="optional" />
        <xs:attribute name="free" type="xs:boolean" use="required"/>
        <xs:attribute name="comment" type="xs:string"/>
        <xs:attribute name="calendar" type="calendars"/>
    </xs:attributeGroup>
    <xs:attributeGroup name="relativeAttributes">
        <xs:attribute name="day" type="dayInt" use="required"/>
        <xs:attribute name="month" type="monthInt" use="required"/>
        <xs:attribute name="relation" type="xs:string" use="required"/>
        <xs:attribute name="free" type="xs:boolean" use="required"/>
        <xs:attribute name="comment" type="xs:string"/>
    </xs:attributeGroup>
    <xs:attributeGroup name="resourceAttributes">
        <xs:attribute name="href" type="xs:anyURI" use="required"/>
        <xs:attribute name="lastChecked" type="xs:date" use="required" />
    </xs:attributeGroup>
    <xs:attributeGroup name="forward">
        <xs:attribute name="forwardto" type="daynames" use="optional"/>
        <xs:attribute name="forwardwhen" type="daynamelist" use="optional" />
		<xs:attribute name="alternateforwardto" type="daynames"/>
		<xs:attribute name="alternateforwardwhen" type="daynamelist"/>
    </xs:attributeGroup>
    <xs:attributeGroup name="rewind">
        <xs:attribute name="rewindto" type="daynames" use="optional"/>
        <xs:attribute name="rewindwhen" type="daynamelist" use="optional" />
		<xs:attribute name="alternaterewindto" type="daynames"/>
		<xs:attribute name="alternaterewindwhen" type="daynamelist"/>
    </xs:attributeGroup>
    <xs:element name="resources">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="resource" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attributeGroup ref="resourceAttributes"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="easter">
		<!--
		Days that are relative to the Easter date as calculated for the
		Western christian churches. The actual day is referenced by an
		offset from easter-sunday. Days before easter sunday have a
		negative offset, days after have a positive offset
		-->
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attributeGroup ref="easterAttributes"/>
					<xs:attributeGroup ref="restriction"/>
					<xs:attributeGroup ref="observanceRestrictions"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="easterorthodox">
		<!--
		Days that are relative to the Easter date as calculated for the
		Eastern Christian churches. The actual day is referenced by an
		offset from easter-sunday. Days before easter sunday have a
		negative offset, days after have a positive offset
		-->
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attributeGroup ref="easterAttributes"/>
					<xs:attributeGroup ref="restriction"/>
					<xs:attributeGroup ref="observanceRestrictions"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="date">
		<!--
		Days that are defined by their actual date like the 4th of July
		or 25th of December.

		The actual day is referenced by at least a day and a month attribute.
		For special occasions where a day is only a holiday in a certain year
		it can also have a year attribute. Note that you will need multiple
		entries for multiple years.
		-->
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attributeGroup ref="dateAttributes"/>
					<xs:attributeGroup ref="rewind"/>
					<xs:attributeGroup ref="forward"/>
					<xs:attributeGroup ref="restriction"/>
					<xs:attributeGroup ref="observanceRestrictions"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="dateFollowUp">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attributeGroup ref="dateFollowUpAttributes"/>
					<xs:attributeGroup ref="restriction"/>
					<xs:attributeGroup ref="observanceRestrictions"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="relative">
		<!--
		This is similar to the dateFollowUp but the relation can be
		more complext.

		Again the date the relation is referenced from is given via
		day and month attributes but the relation itself is given in
		the relation attribute and can be anything that
		http://php.net/manual/de/datetimeimmutable.modify.php
		can handle. Like "last sunday -3 weeks" from 25th of december
		would be the 1st sunday in advent
		-->
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attributeGroup ref="relativeAttributes"/>
					<xs:attributeGroup ref="restriction"/>
					<xs:attributeGroup ref="rewind"/>
					<xs:attributeGroup ref="forward"/>
					<xs:attributeGroup ref="observanceRestrictions"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>



	<xs:element name="holidays">
        <!--
        All elements have to be within the root element "holidays".

        Within this root element we expect a list of entries of type
        "easter", "easterorthodox", "date", "dateFollowUp" or "relative"

        Explanations follow on the respective elements
        -->
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element ref="resources" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="easter" minOccurs="0" maxOccurs="unbounded" />
                <xs:element ref="easterorthodox" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="date" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="dateFollowUp" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="relative" minOccurs="0" maxOccurs="unbounded" />
            </xs:choice>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== dweichert/holidayChecker/share/HU.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
					xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
					xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
					xmlns:xi="http://www.w3.org/2001/XInclude"
>
	<resources>
		<resource href="https://en.wikipedia.org/wiki/Public_holidays_in_Hungary" lastChecked="2024-01-17">Wikipedia</resource>
	</resources>
	<date day="1" month="1" free="true" comment="New years day">Újév</date>
	<date day="15" month="3" free="true" comment="National Day">Nemzeti ünnep</date>
	<easter offset="-2" free="true" comment="Good Friday" firstobservance="2017">Nagypéntek</easter>
	<easter offset="1" free="true" comment="Easter Monday">Húsvéthétfő</easter>
	<date day="1" month="5" free="true" comment="Labour day">A munka ünnepe</date>
	<easter offset="50" free="true" comment="Whit Monday">Pünkösdhétfő</easter>
	<date day="20" month="8" free="true" comment="State foundation day">Az államalapítás ünnepe</date>
	<date day="23" month="10" free="true" comment="National Day">Nemzeti ünnep</date>
	<date day="1" month="11" free="true" comment="All Saints Day">Mindenszentek</date>
	<date day="25" month="12" free="true" comment="Christmas Day">Karácsony</date>
	<date day="26" month="12" free="true" comment="Second day of christmas">Karácsony másnapja</date>
	<date day="22" month="1" free="false" comment="Day of the Hungarian Culture">A magyar kultúra napja</date>
	<date day="1" month="2" free="false" comment="Memorial Day of the Republic">A köztársaság emléknapja</date>
	<date day="25" month="2" free="false" comment="Memorial Day for the vivtims of the Communist Dictatorship">A kommunista diktatúrák áldozatainak emléknapja</date>
	<date day="16" month="4" free="false" comment="Memorial Day for the victims of the Holocaust">A holokauszt áldozatainak emléknapja</date>
	<date day="21" month="5" free="false" comment="National Defense Day">Honvédelmi nap</date>
	<date day="4" month="6" free="false" comment="National Unity Day">A nemzeti összetartozás napja </date>
	<date day="19" month="6" free="false" comment="Independen Hungary Day">A független Magyarország napja</date>
	<date day="6" month="10" free="false" comment="Memorial Day for the Martyrs of Arad">Az aradi vértanúk emléknapja</date>
</holidays>

=== dweichert/holidayChecker/share/HR.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
					xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
					xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
					xmlns:xi="http://www.w3.org/2001/XInclude"
>
	<resources>
		<resource href="https://en.wikipedia.org/wiki/Public_holidays_in_Croatia" lastChecked="2023-08-05">Wikipedia</resource>
	</resources>
	<date day="1" month="1" free="true" comment="New Year's Day">Nova godina</date>
	<date day="6" month="1" free="true" comment="Epiphany">Sveta tri kralja</date>
	<easter offset="0" free="true" comment="Easter">Uskrs</easter>
	<easter offset="1" free="true" comment="Easter Monday">Uskrsni ponedjeljak</easter>
	<date day="1" month="5" free="true" comment="Labour Day">Praznik rada</date>
	<date day="30" month="5" free="true" comment="National Day" firstobservance="1991" lastobservance="2001">Dan državnosti</date>
	<date day="30" month="5" free="true" comment="National Day" firstobservance="2020">Dan državnosti</date>
	<date day="30" month="5" free="false" comment="Day of the Croatian Parliament" firstobservance="2002" lastobservance="2019">Dan Hrvatskoga sabora</date>
	<easter offset="60" free="true" comment="Corpus Christi">Tijelovo</easter>
	<date day="22" month="6" free="true" comment="Anti-Fascist Struggle Day">Dan antifašističke borbe</date>
	<date day="5" month="8" free="true" comment="Victory and Homeland Thanksgiving Day">Dan pobjede i domovinske zahvalnosti</date>
	<date day="15" month="8" free="true" comment="Assumption of Mary">Velika Gospa</date>
	<date day="1" month="11" free="true" comment="All Saint's Day">Dan svih svetih</date>
	<date day="18" month="11" free="true" comment="Day of Remembrance of Victims of the Homeland War" firstobservance="2020">Dan sjećanja na žrtve Domovinskog rata</date>
	<date day="25" month="12" free="true" comment="Christmas">Božić</date>
	<date day="26" month="12" free="true" comment="Saint Stephen's Day">Sveti Stjepan</date>
	<date day="9" month="1" free="false" comment="Day of Unification of Medimurje with its Parent Body Croatia">Dan sjedinjenja Medimurja s maticom zemljom Hrvatskom</date>
	<date day="15" month="1" free="false" comment="Day of international recognition of the Republic of Croatia and Day of peaceful reintegration of the Croatian Danube Region">Dan međunarodnoga priznanja Republike Hrvatske i Dan mirne reintegracije hrvatskog Podunavlja </date>
	<date day="15" month="3" free="false" comment="Day of founding of the People's Prodection">Dan osnivanja Narodne zaštite</date>
	<date day="30" month="4" free="false" comment="Day of the Death of Zrinski and Frankopan">Dan pogibije Zrinskog i Frankopana</date>
	<date day="9" month="5" free="false" comment="Europe Day and Day of vitory over fascism">Dan Europe i Dan pobjede nad fašizmom</date>
	<date day="15" month="5" free="false" alternateforwardto="saturday" alternateforwardwhen="wednesday thursday friday" alternaterewindto="sunday" alternaterewindwhen="monday tuesday" comment="Day of Remembrance of Croatian Victims in the Fight for Freedom and Independence">Dan spomena na hrvatske žrtve u borbi za slobodu i nezavisnost</date>
	<date day="25" month="6" free="true" comment="Statehood Day" lastobservance="2019">Dan neovisnosti</date>
	<date day="25" month="6" free="false" comment="Independence Day" firstobservance="2020">Dan neovisnosti</date>
	<date day="23" month="8" free="false" comment="European Day of Remembrance for Victims of Stalinism and Nazism">Europski dan sjećanja na žrtve totalitarnih i autoritarnih režima – nacizma, fašizma i komunizma </date>
	<date day="30" month="8" free="false" comment="Day of Remembrance of Missing Persons in the War of Independence">Dan sjećanja na nestale osobe u Domovinskom ratu</date>
	<date day="25" month="9" free="false" comment="Day of the Deciscion about the Unification of Istria, Rijeka, Zadar and the Islands with the Parent Body Croatia ">Dan donošenja Odluke o sjedinjenju Istre, Rijeke, Zadra i otoka s maticom zemljom Hrvatskom </date>
	<date day="8" month="10" free="false" comment="Day of the Croatian Parliament" firstobservance="2020">Dan Hrvatskoga sabora</date>
	<date day="8" month="10" free="true" comment="Independence Day" lastobservance="2019">Dan neovisnosti</date>
</holidays>

=== dweichert/holidayChecker/share/CZ.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
					xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
					xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
					xmlns:xi="http://www.w3.org/2001/XInclude"
>
	<resources>
		<resource href="https://en.wikipedia.org/wiki/Public_holidays_in_the_Czech_Republic" lastChecked="2023-08-05">Wikipedia</resource>
	</resources>
	<date day="1" month="1" free="true" comment="Restoration Day of the Independent Czech State, New Year's Day">Den obnovy samostatného českého státu; Nový rok</date>
	<easter offset="-2" free="true" comment="Good Friday">Velký pátek</easter>
	<easter offset="1" free="true" comment="Easter Monday">Velikonoční pondělí</easter>
	<date day="1" month="5" free="true" comment="Labour Day">Svátek práce</date>
	<date day="8" month="5" free="true" comment="Victory Day">Den vítězství</date>
	<date day="5" month="7" free="true" comment="Saints Cyril and Methodius Day">Den slovanských věrozvěstů Cyrila a Metoděje</date>
	<date day="6" month="7" free="true" comment="Jan Hus Day">Den upálení mistra Jana Husa</date>
	<date day="28" month="9" free="true" comment="Statehood Day">Den české státnosti</date>
	<date day="28" month="10" free="true" comment="Independent Czechoslovak State Day">Den vzniku samostatného československého státu</date>
	<date day="17" month="11" free="true" comment="Struggle for Freedom and Democracy Day">Den boje za svobodu a demokracii</date>
	<date day="24" month="12" free="true" comment="CHristmas Eve">Štědrý den</date>
	<date day="25" month="12" free="true" comment="Christmas Day">1. svátek vánoční</date>
	<date day="26" month="12" free="true" comment="St. Stephen's Day">2. svátek vánoční</date>
</holidays>

=== dweichert/holidayChecker/share/US.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="https://heigl.org/holidays https://heigl.org/xml/xsd/holidays.xsd"
>
    <date day="1" month="1" free="true">New Year's Day</date>
    <relative day="1" month="1" relation="third monday of this month" free="true">Birthday of Martin Luther King, Jr.</relative>
    <relative day="1" month="2" relation="third monday of this month" free="true">Washington's Birthday</relative>
    <relative day="1" month="5" relation="last monday of this month" free="true">Memorial Day</relative>
    <date day="19" month="6" free="true">Juneteenth National Independence Day</date>
    <date day="4" month="7" free="true">Independence Day</date>
    <relative day="1" month="9" relation="first monday of this month" free="true">Labor Day</relative>
    <relative day="1" month="10" relation="second monday of this month" free="true">Columbus Day</relative>
    <date day="11" month="11" free="true">Veterans Day</date>
    <relative day="1" month="11" relation="fourth thursday of this month" free="true">Thanksgiving Day</relative>
    <date day="25" month="12" free="true">Christmas Day</date>
    <resources>
        <resource href="https://en.wikipedia.org/wiki/Federal_holidays_in_the_United_States" lastChecked="2022-12-14">
            Wikipedia
        </resource>
    </resources>
</holidays>

=== dweichert/holidayChecker/share/KM.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
					xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
					xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
					xmlns:xi="http://www.w3.org/2001/XInclude"
>
	<resources>
		<resource href="https://en.wikipedia.org/wiki/Public_holidays_in_the_Comoros" lastChecked="2023-08-05">Wikipedia</resource>
	</resources>
	<date day="1" month="1" free="true">New Year's Day</date>
	<date day="18" month="3" free="true">Cheikh Al Maarouf Day</date>
	<date day="1" month="5" free="true">Labour Day</date>
	<date day="6" month="7" free="true">National Day</date>
	<date day="12" month="11" free="true" firstobservance="2006">Maore Day</date>
	<date day="1" month="10" free="true" calendar="islamic">Eid al-Fitr</date>
	<date day="10" month="12" free="true" calendar="islamic">Eid al-Adha</date>
	<date day="1" month="1" free="true" calendar="islamic">Islamic New Year</date>
	<date day="12" month="3" free="true" calendar="islamic" comment="Birthday of the Prophet">Mawlid</date>
	<date day="27" month="7" free="true" calendar="islamic" comment="Ascension of the Prophet">Laylat al-Mi'raj</date>
</holidays>

=== dweichert/holidayChecker/share/DE.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="https://heigl.org/xml/xsd/holidays.xsd"
>
    <date day="1" month="1" free="true">Neujahr</date>
    <date day="6" month="1" free="false">Epiphanias</date>
    <easter offset="-2" free="true">Karfreitag</easter>
    <easter offset="1" free="true">Ostermontag</easter>
    <easter offset="0" free="false">Ostersonntag</easter>
    <date day="1" month="5" free="true">Maifeiertag</date>
    <easter offset="49" free="false">Pfingstsonntag</easter>
    <easter offset="50" free="true">Pfingstmontag</easter>
    <easter offset="39" free="true">Christi Himmelfahrt</easter>
    <easter offset="60" free="false">Fronleichnam</easter>
    <date day="15" month="8" free="false">Mariä Himmelfahrt</date>
    <date day="3" month="10" free="true">Tag d. Dt. Einheit</date>
    <date day="31" month="10" year="2017" free="true">Reformationstag</date>
    <date day="31" month="10" free="false">Reformationstag</date>
    <date day="1" month="11" free="false">Allerheiligen</date>
    <relative day="23" month="11" free="false" relation="last wednesday">Buß- und Bettag</relative>
    <relative day="25" month="12" free="false" relation="last sunday -3 weeks">1. Advent</relative>
    <relative day="25" month="12" free="false" relation="last sunday -2 weeks">2. Advent</relative>
    <relative day="25" month="12" free="false" relation="last sunday -1 weeks">3. Advent</relative>
    <relative day="25" month="12" free="false" relation="last sunday">4. Advent</relative>
    <date day="24" month="12" free="false">Heiligabend</date>
    <date day="25" month="12" free="true">1. Weihnachtstag</date>
    <date day="26" month="12" free="true">2. Weihnachtstag</date>
    <date day="31" month="12" free="false">Silvester</date>
</holidays>
