=== dweichert/holidayChecker/share/holidays.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://heigl.org/holidays"
           xmlns="https://heigl.org/holidays"
           elementFormDefault="qualified">
    <xs:simpleType name="monthInt">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="12"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="dayInt">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="31"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="daynames">
        <xs:restriction base="xs:string">
            <xs:enumeration value="sunday"/>
            <xs:enumeration value="monday"/>
            <xs:enumeration value="tuesday"/>
            <xs:enumeration value="wednesday"/>
            <xs:enumeration value="thursday"/>
            <xs:enumeration value="friday"/>
            <xs:enumeration value="saturday"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="daynamelist">
        <xs:list itemType="daynames" />
    </xs:simpleType>
    <xs:simpleType name="calendars">
        <xs:restriction base="xs:string">
			<!--
			as described in the language files of ICU
			see https://github.com/unicode-org/icu/blob/d453c12bfacde783b7e985cdb4eb15c6db277f78/icu4c/source/data/lang/en.txt#L951-L970
			-->
            <xs:enumeration value="buddhist"/>
            <xs:enumeration value="chinese"/>
            <xs:enumeration value="coptic"/>
            <xs:enumeration value="dangi"/>
            <xs:enumeration value="ethiopic"/>
            <xs:enumeration value="ethiopic-amete-alem"/>
            <xs:enumeration value="gregorian"/>
            <xs:enumeration value="hebrew"/>
            <xs:enumeration value="indian"/>
            <xs:enumeration value="islamic"/>
            <xs:enumeration value="islamic-civil"/>
            <xs:enumeration value="islamic-umalqura"/>
            <xs:enumeration value="islamic-tbla"/>
            <xs:enumeration value="iso8601"/>
            <xs:enumeration value="japanese"/>
            <xs:enumeration value="persian"/>
            <xs:enumeration value="roc"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:attributeGroup name="restriction">
        <xs:attribute name="restriction" type="xs:string" />
    </xs:attributeGroup>
	<xs:attribute name="firstobservance" type="xs:gYear"/>
	<xs:attribute name="lastobservance" type="xs:gYear"/>
    <xs:attributeGroup name="observanceRestrictions">
		<xs:annotation xml:lang="en">
			<xs:documentation>
				The attributes firstobservance and lastobservance are including.
				The attribute interval describes that the holiday is only observed every $interval years with the first observance in year $firstobservance.
			</xs:documentation>
		</xs:annotation>
        <xs:attribute name="firstobservance" type="xs:gYear"/>
        <xs:attribute name="lastobservance" type="xs:gYear"/>
		<xs:attribute name="interval" type="xs:integer"/>
    </xs:attributeGroup>
	<xs:attributeGroup name="observanceInterval">
		<xs:attribute ref="firstobservance" use="required"/>
	</xs:attributeGroup>
    <xs:attributeGroup name="easterAttributes">
        <xs:attribute name="offset" type="xs:integer" use="required"/>
        <xs:attribute name="free" type="xs:boolean" use="required"/>
        <xs:attribute name="comment" type="xs:string"/>
    </xs:attributeGroup>
    <xs:attributeGroup name="dateAttributes">
        <xs:attribute name="day" type="dayInt" use="required"/>
        <xs:attribute name="month" type="monthInt" use="required"/>
        <xs:attribute name="year" type="xs:integer" />
        <xs:attribute name="free" type="xs:boolean" use="required"/>
        <xs:attribute name="comment" type="xs:string"/>
        <xs:attribute name="calendar" type="calendars"/>
    </xs:attributeGroup>
    <xs:attributeGroup name="dateFollowUpAttributes">
        <xs:attribute name="day" type="dayInt" use="required"/>
        <xs:attribute name="month" type="monthInt" use="required"/>
        <xs:attribute name="followup" type="daynames" use="required" />
        <xs:attribute name="replaced" type="daynamelist" use="optional" />
        <xs:attribute name="free" type="xs:boolean" use="required"/>
        <xs:attribute name="comment" type="xs:string"/>
        <xs:attribute name="calendar" type="calendars"/>
    </xs:attributeGroup>
    <xs:attributeGroup name="relativeAttributes">
        <xs:attribute name="day" type="dayInt" use="required"/>
        <xs:attribute name="month" type="monthInt" use="required"/>
        <xs:attribute name="relation" type="xs:string" use="required"/>
        <xs:attribute name="free" type="xs:boolean" use="required"/>
        <xs:attribute name="comment" type="xs:string"/>
    </xs:attributeGroup>
    <xs:attributeGroup name="resourceAttributes">
        <xs:attribute name="href" type="xs:anyURI" use="required"/>
        <xs:attribute name="lastChecked" type="xs:date" use="required" />
    </xs:attributeGroup>
    <xs:attributeGroup name="forward">
        <xs:attribute name="forwardto" type="daynames" use="optional"/>
        <xs:attribute name="forwardwhen" type="daynamelist" use="optional" />
		<xs:attribute name="alternateforwardto" type="daynames"/>
		<xs:attribute name="alternateforwardwhen" type="daynamelist"/>
    </xs:attributeGroup>
    <xs:attributeGroup name="rewind">
        <xs:attribute name="rewindto" type="daynames" use="optional"/>
        <xs:attribute name="rewindwhen" type="daynamelist" use="optional" />
		<xs:attribute name="alternaterewindto" type="daynames"/>
		<xs:attribute name="alternaterewindwhen" type="daynamelist"/>
    </xs:attributeGroup>
    <xs:element name="resources">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="resource" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attributeGroup ref="resourceAttributes"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="easter">
		<!--
		Days that are relative to the Easter date as calculated for the
		Western christian churches. The actual day is referenced by an
		offset from easter-sunday. Days before easter sunday have a
		negative offset, days after have a positive offset
		-->
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attributeGroup ref="easterAttributes"/>
					<xs:attributeGroup ref="restriction"/>
					<xs:attributeGroup ref="observanceRestrictions"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="easterorthodox">
		<!--
		Days that are relative to the Easter date as calculated for the
		Eastern Christian churches. The actual day is referenced by an
		offset from easter-sunday. Days before easter sunday have a
		negative offset, days after have a positive offset
		-->
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attributeGroup ref="easterAttributes"/>
					<xs:attributeGroup ref="restriction"/>
					<xs:attributeGroup ref="observanceRestrictions"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="date">
		<!--
		Days that are defined by their actual date like the 4th of July
		or 25th of December.

		The actual day is referenced by at least a day and a month attribute.
		For special occasions where a day is only a holiday in a certain year
		it can also have a year attribute. Note that you will need multiple
		entries for multiple years.
		-->
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attributeGroup ref="dateAttributes"/>
					<xs:attributeGroup ref="rewind"/>
					<xs:attributeGroup ref="forward"/>
					<xs:attributeGroup ref="restriction"/>
					<xs:attributeGroup ref="observanceRestrictions"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="dateFollowUp">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attributeGroup ref="dateFollowUpAttributes"/>
					<xs:attributeGroup ref="restriction"/>
					<xs:attributeGroup ref="observanceRestrictions"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="relative">
		<!--
		This is similar to the dateFollowUp but the relation can be
		more complext.

		Again the date the relation is referenced from is given via
		day and month attributes but the relation itself is given in
		the relation attribute and can be anything that
		http://php.net/manual/de/datetimeimmutable.modify.php
		can handle. Like "last sunday -3 weeks" from 25th of december
		would be the 1st sunday in advent
		-->
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attributeGroup ref="relativeAttributes"/>
					<xs:attributeGroup ref="restriction"/>
					<xs:attributeGroup ref="rewind"/>
					<xs:attributeGroup ref="forward"/>
					<xs:attributeGroup ref="observanceRestrictions"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>



	<xs:element name="holidays">
        <!--
        All elements have to be within the root element "holidays".

        Within this root element we expect a list of entries of type
        "easter", "easterorthodox", "date", "dateFollowUp" or "relative"

        Explanations follow on the respective elements
        -->
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element ref="resources" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="easter" minOccurs="0" maxOccurs="unbounded" />
                <xs:element ref="easterorthodox" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="date" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="dateFollowUp" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="relative" minOccurs="0" maxOccurs="unbounded" />
            </xs:choice>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== dweichert/holidayChecker/share/CH-FR.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
					xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
					xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
					xmlns:xi="http://www.w3.org/2001/XInclude"
>
	<resources>
		<resource href="https://en.wikipedia.org/wiki/Public_holidays_in_Switzerland" lastChecked="2023-04-21">Wikipedia</resource>
	</resources>
	<date day="1" month="1" free="true">Neujahrstag</date>
	<date day="2" month="1" free="true" restriction="despite not being an official holiday mostly free">Berchtoldstag</date>
	<date day="19" month="3" free="true" restriction="only in some municipalities">Josefstag</date>
	<easter offset="-2" free="true">Karfreitag</easter>
	<easter offset="1" free="true" restriction="despite not being an official holiday mostly free">Ostermontag</easter>
	<date day="1" month="5" free="true" restriction="starts at 12:00; only for public employees; usually observed by everyone">Tag der Arbeit</date>
	<easter offset="39" free="true">Auffahrt</easter>
	<easter offset="50" free="true" restriction="despite not being an official holiday mostly free">Pfingstmontag</easter>
	<easter offset="60" free="true" restriction="only in some municipalities">Frohnleichnam</easter>
	<date day="1" month="8" free="true">Bundesfeier</date>
	<date day="15" month="8" free="true" restriction="only in some municipalities">Mariä Himmelfahrt</date>
	<date day="1" month="11" free="true" restriction="only in some municipalities">Allerheiligen</date>
	<date day="8" month="12" free="true" restriction="only in some municipalities">Mariä Empfängnis</date>
	<date day="25" month="12" free="true">Weihnachtstag</date>
	<date day="26" month="12" free="true">Stephanstag</date>
</holidays>

=== dweichert/holidayChecker/share/CH-SZ.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
					xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
					xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
					xmlns:xi="http://www.w3.org/2001/XInclude"
>
	<resources>
		<resource href="https://en.wikipedia.org/wiki/Public_holidays_in_Switzerland" lastChecked="2023-04-21">Wikipedia</resource>
	</resources>
	<date day="1" month="1" free="true">Neujahrstag</date>
	<date day="6" month="1" free="true">Heilige Drei Könige</date>
	<date day="19" month="3" free="true">Josefstag</date>
	<easter offset="-2" free="true">Karfreitag</easter>
	<easter offset="1" free="true">Ostermontag</easter>
	<easter offset="39" free="true">Auffahrt</easter>
	<easter offset="50" free="true">Pfingstmontag</easter>
	<easter offset="60" free="true">Frohnleichnam</easter>
	<date day="1" month="8" free="true">Bundesfeier</date>
	<date day="15" month="8" free="true">Mariä Himmelfahrt</date>
	<date day="1" month="11" free="true">Allerheiligen</date>
	<date day="8" month="12" free="true">Mariä Empfängnis</date>
	<date day="25" month="12" free="true">Weihnachtstag</date>
	<date day="26" month="12" free="true">Stephanstag</date>
</holidays>

=== dweichert/holidayChecker/share/CR.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
					xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
					xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
					xmlns:xi="http://www.w3.org/2001/XInclude"
>
	<resources>
		<resource href="https://en.wikipedia.org/wiki/Public_holidays_in_Costa_Rica" lastChecked="2023-08-05">Wikipedia</resource>
	</resources>
	<date day="1" month="1" free="true" comment="New Year's Day">Año Nuevo</date>
	<easter offset="-3" free="true" comment="Maundy Thursday">Jueves Santo</easter>
	<easter offset="-2" free="true" comment="Good Friday">Viernes Santo</easter>
	<date day="11" month="4" free="true" comment="Juan Santamaría Day">Día de Juan Santamaría</date>
	<date day="1" month="5" free="true" comment="Labour Day">Día Internacional del Trabajo</date>
	<date day="25" month="7" free="true" comment="Annexation of the Party of Nicoya to Costa Rica">Anexión del Partido de Nicoya a Costa Rica</date>
	<date day="2" month="8" free="true" comment="Feat of our Lady of the Angels">Fiesta de Nuestra Señora de los Ángeles</date>
	<date day="15" month="8" free="true" comment="Mothers Day">Día de la Madre</date>
	<date day="24" month="8" free="true" comment="National Parks Day">Día de los Parques Nacionales</date>
	<date day="9" month="9" free="true">Día del Niño</date>
	<date day="13" month="9" free="true" comment="Independence Day">Día de la Independencia</date>
	<date day="1" month="12" free="true" comment="Army Abolition Day">Día de la Abolición del Ejército</date>
	<date day="25" month="12" free="true" comment="Christmas Day">Navidad</date>
</holidays>

=== dweichert/holidayChecker/share/CG.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
					xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
					xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
					xmlns:xi="http://www.w3.org/2001/XInclude"
>
	<resources>
		<resource href="https://en.wikipedia.org/wiki/Public_holidays_in_the_Republic_of_the_Congo" lastChecked="2023-08-05">Wikipedia</resource>
	</resources>
	<date day="1" month="1" free="true" comment="New Year's Day">Jour de l'An</date>
	<date day="1" month="5" free="true" comment="Labours Day">Fête du Travail</date>
	<date day="10" month="6" free="true" comment="Reconciliation Day">Fête de la Réconciliation</date>
	<date day="15" month="8" free="true" comment="National Day">Fête Nationale</date>
	<date day="1" month="11" free="true" comment="All Saints Day">Toussaint</date>
	<date day="28" month="11" free="true" comment="Republic Day">Jour de la République</date>
	<date day="25" month="12" free="true" comment="Christmas Day">Noël</date>
	<easter offset="1" free="true" comment="Easter Monday">Lundi de Pâques</easter>
	<easter offset="40" free="true" comment="Ascension Day">Ascension</easter>
	<easter offset="50" free="true" comment="Whit Monday">Lundi de Pentecôte</easter>
</holidays>

=== dweichert/holidayChecker/share/CU.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
					xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
					xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
					xmlns:xi="http://www.w3.org/2001/XInclude"
>
	<resources>
		<resource href="https://en.wikipedia.org/wiki/Public_holidays_in_Cuba" lastChecked="2023-08-05">Wikipedia</resource>
	</resources>
	<date day="1" month="1" free="true" comment="Liberation Day">Día de la Liberación</date>
	<date day="2" month="1" free="true" comment="Victory Day">Día de la Victoria</date>
	<easter offset="-2" free="true" comment="Good Friday" firstobservance="2012">Viernes Santo</easter>
	<date day="1" month="5" free="true" comment="International Worker's Day">Día de los trabajadores</date>
	<date day="25" month="7" free="true" comment="Day before the Commemoration of the Assault on the Moncada Garrison">Conmemoración del asalto a Moncada</date>
	<date day="26" month="7" free="true" comment="Commemoration of the Assault on the Moncada Garrison">Día de la Rebeldía Nacional</date>
	<date day="27" month="7" free="true" comment="Day after the Commemoration of the Assault on the Moncada Garrison">Conmemoración del asalto a Moncada</date>
	<date day="10" month="10" free="true" comment="Independence Day">Día de la Independencia</date>
	<date day="25" month="12" free="true" comment="Christmas Day" firstobservance="1998">Navidad</date>
</holidays>

=== dweichert/holidayChecker/share/CY.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
					xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
					xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
					xmlns:xi="http://www.w3.org/2001/XInclude"
>
	<resources>
		<resource href="https://www.centralbank.cy/images/media/pdf/Bank-Holidays-2025-English.pdf" lastChecked="2023-08-05">Bank of Cyprus - english</resource>
		<resource href="https://www.centralbank.cy/images/media/pdf_el/Bank-Holidays-2025-Greek.pdf" lastChecked="2023-08-05">Bank of Cyprus - greek</resource>
		<resource href="https://en.wikipedia.org/wiki/Public_holidays_in_Cyprus" lastChecked="2023-08-05">Wikipedia</resource>
	</resources>
	<date day="1" month="1" free="true" comment="New Year's Day">Πρωτοχρονιά</date>
	<date day="6" month="1" free="true" comment="Epiphany Day">Ημέρα των Θεοφανίων</date>
	<easterorthodox offset="-48" free="true" comment="Green Monday">Καθαρά Δευτέρα</easterorthodox>
	<date day="25" month="3" free="true" comment="Greek Independence Day">Ημέρα της Ελληνικής Ανεξαρτησίας</date>
	<date day="1" month="4" free="true" comment="Cyprus National Day">Εθνική Γιορτή</date>
	<easterorthodox offset="-2" free="true" comment="Good Friday">Μεγάλη Παρασκευή</easterorthodox>
	<easterorthodox offset="1" free="true" comment="Easter Monday">Δευτέρα της Διακαινησίμου</easterorthodox>
	<easterorthodox offset="2" free="true" comment="Easter Tuesday">Τρίτη της Διακαινησίμου</easterorthodox>
	<date day="1" month="5" free="true" comment="Labour Day">Πρωτομαγιά</date>
	<easterorthodox offset="50" free="true" comment="Pentecost">Δευτέρα του Αγίου Πνεύματος</easterorthodox>
	<date day="15" month="8" free="true" comment="Assumption Day">Κοίμηση της Θεοτόκου</date>
	<date day="1" month="10" free="true" comment="Cyprus Independence Day">Ημέρα της Κυπριακής Ανεξαρτησίας</date>
	<date day="28" month="10" free="true" comment="Greek National Day">Εθνική Γιορτή</date>
	<date day="25" month="12" free="true" comment="Christmas Day">Χριστούγεννα</date>
	<date day="26" month="12" free="true" comment="Boxing Day">Επομένη Χριστουγέννων</date>
</holidays>

=== dweichert/holidayChecker/share/CO.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
					xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
					xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
					xmlns:xi="http://www.w3.org/2001/XInclude"
>
	<resources>
		<resource href="https://en.wikipedia.org/wiki/Public_holidays_in_Colombia" lastChecked="2023-08-05"></resource>
	</resources>
	<date day="1" month="1" free="true" comment="New Years Day">Año Nuevo</date>
	<date day="6" month="1" free="true" comment="Epiphany">Día de los Reyes Magos</date>
	<date day="19" month="3" free="true" comment="St. Josephs Day">Día de San José</date>
	<easter offset="-3" free="true" comment="Maundy Thursday">Jueves Santo</easter>
	<easter offset="-2" free="true" comment="Good Friday">Viernes Santo</easter>
	<easter offset="0" free="true" comment="Easter Sunday">Easter Sunday</easter>
	<date day="1" month="5" free="true" comment="Labour Day">Primero de Mayo</date>
	<easter offset="39" free="true" comment="Ascension of Jesus">Ascensión del señor</easter>
	<easter offset="60" free="true">Corpus Christi</easter>
	<easter offset="68" free="true" comment="Sacred Heart">Sagrado Corazón</easter>
	<date day="29" month="6" free="true" comment="Saint Peter and Saint Paul">San Pedro y San Pablo</date>
	<date day="20" month="7" free="true" comment="Declaration of independence">Declaración de la Independencia de Colombia</date>
	<date day="7" month="8" free="true">Battle of Boyacá</date>
	<date day="15" month="8" free="true" comment="Assumption of Mary">La Asunción</date>
	<date day="12" month="10" free="true" comment="Columbus Day">Día de la Raza</date>
	<date day="1" month="11" free="true" comment="All Saints Day">Día de los Santos</date>
	<date day="11" month="11" free="true" comment="Independence from Cartagena">Independencia de Cartagena</date>
	<date day="8" month="12" free="true" comment="Immaculate conception">La Inmaculada Concepción</date>
	<date day="25" month="12" free="true" comment="Christmas">Navidad</date>
	<easter offset="-48" free="true" comment="Carnival Monday" restriction="only in the city of Barranquilla">Carnival Monday</easter>
	<easter offset="-47" free="true" comment="Carnival Tuesday" restriction="only in the city of Barranquilla">Carnival Tuesday</easter>
</holidays>

=== dweichert/holidayChecker/share/CH-BE.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
					xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
					xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
					xmlns:xi="http://www.w3.org/2001/XInclude"
>
	<resources>
		<resource href="https://en.wikipedia.org/wiki/Public_holidays_in_Switzerland" lastChecked="2023-04-21">Wikipedia</resource>
	</resources>
	<date day="1" month="1" free="true">Neujahrstag</date>
	<date day="2" month="1" free="true" >Berchtoldstag</date>
	<easter offset="-2" free="true">Karfreitag</easter>
	<easter offset="1" free="true">Ostermontag</easter>
	<easter offset="39" free="true">Auffahrt</easter>
	<easter offset="50" free="true">Pfingstmontag</easter>
	<date day="1" month="8" free="true">Bundesfeier</date>
	<date day="25" month="12" free="true">Weihnachtstag</date>
	<date day="26" month="12" free="true">Stephanstag</date>
</holidays>
